apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - gw1
  http:
  - match:
      - uri:
          prefix: /
    route:
